/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AirlinesRouteImport } from './routes/airlines'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ServiceRouteImport } from './routes/$service'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServiceIndexRouteImport } from './routes/$service.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ServiceAirlineRouteImport } from './routes/$service.$airline'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AirlinesRoute = AirlinesRouteImport.update({
  id: '/airlines',
  path: '/airlines',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ServiceIndexRoute = ServiceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ServiceAirlineRoute = ServiceAirlineRouteImport.update({
  id: '/$airline',
  path: '/$airline',
  getParentRoute: () => ServiceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$service': typeof ServiceRouteWithChildren
  '/about': typeof AboutRoute
  '/airlines': typeof AirlinesRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$service/$airline': typeof ServiceAirlineRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/$service/': typeof ServiceIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airlines': typeof AirlinesRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$service/$airline': typeof ServiceAirlineRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/$service': typeof ServiceIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$service': typeof ServiceRouteWithChildren
  '/about': typeof AboutRoute
  '/airlines': typeof AirlinesRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$service/$airline': typeof ServiceAirlineRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/$service/': typeof ServiceIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$service'
    | '/about'
    | '/airlines'
    | '/blog'
    | '/contact'
    | '/sitemap.xml'
    | '/$service/$airline'
    | '/blog/$slug'
    | '/$service/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/airlines'
    | '/contact'
    | '/sitemap.xml'
    | '/$service/$airline'
    | '/blog/$slug'
    | '/$service'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/$service'
    | '/about'
    | '/airlines'
    | '/blog'
    | '/contact'
    | '/sitemap.xml'
    | '/$service/$airline'
    | '/blog/$slug'
    | '/$service/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServiceRoute: typeof ServiceRouteWithChildren
  AboutRoute: typeof AboutRoute
  AirlinesRoute: typeof AirlinesRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airlines': {
      id: '/airlines'
      path: '/airlines'
      fullPath: '/airlines'
      preLoaderRoute: typeof AirlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$service': {
      id: '/$service'
      path: '/$service'
      fullPath: '/$service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/$service/': {
      id: '/$service/'
      path: '/'
      fullPath: '/$service/'
      preLoaderRoute: typeof ServiceIndexRouteImport
      parentRoute: typeof ServiceRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/$service/$airline': {
      id: '/$service/$airline'
      path: '/$airline'
      fullPath: '/$service/$airline'
      preLoaderRoute: typeof ServiceAirlineRouteImport
      parentRoute: typeof ServiceRoute
    }
  }
}

interface ServiceRouteChildren {
  ServiceAirlineRoute: typeof ServiceAirlineRoute
  ServiceIndexRoute: typeof ServiceIndexRoute
}

const ServiceRouteChildren: ServiceRouteChildren = {
  ServiceAirlineRoute: ServiceAirlineRoute,
  ServiceIndexRoute: ServiceIndexRoute,
}

const ServiceRouteWithChildren =
  ServiceRoute._addFileChildren(ServiceRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServiceRoute: ServiceRouteWithChildren,
  AboutRoute: AboutRoute,
  AirlinesRoute: AirlinesRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
